### ISSUE TITLE
Problem with datepicker layout

### ISSUE THREAD

**Issue by v105568** [vanpra/compose-material-dialogs#100]
I have a problem with datepicker in 0.5.1. When flipping pages, if the current or neighboring month has 6 weeks, horisontalpager takes an additional height, and this violates the layout. The confirmation buttons go off the screen.

And an additional wish. I would be grateful if you can pass the names of the days of the weeks as parameter. This is important for localization.

**Comment by j-osephlong** [comment]
Same issue here.

**Comment by vanpra** [comment]
Thanks for raising this issue. I've tried to reproduce this on my device but haven't been able to. Could you please check if this is still a bug in the 0.6.0 and if so could you provide some details about the device you are experiencing this issue on?

**Comment by ntoskrnl** [comment]
@vanpra It looks like the issue is fixed. I could reproduce the layout bug on 0.5.1. Now, on 0.6.0 everything's works fine.

The bug with flipping pages appeared only when the dialog is opened with certain initial date. Also, there was similar issue when I open year selection (when the car range is large enough). Maybe screen size also plays some role here.

**Comment by ntoskrnl** [comment]
I noticed that when I change screen orientation to landscape on the phone, the dialog doesn't fit into the screen and buttons are cut off. Is there anything that can be done about it?

**Comment by ntoskrnl** [comment]
Here is another case that shows the bug when content of the dialog doesn't fit. 
It happens when soft keyboard was previously displayed and I try to open the date picket dialog:

https://user-images.githubusercontent.com/1446492/133707624-d24f8600-c89b-4017-b08f-158e665b3778.mp4

Device is Pixel 2 XL.

**Comment by vanpra** [comment]
Thanks for letting me know I'll keep track of the buttons cutting off in #118
