### ISSUE TITLE
Datetime picker

### ISSUE THREAD

**Issue by lprendergast-mum** [vanpra/compose-material-dialogs#117]
In version 0.4.3 we had the possibility of adding a datetime picker. Now that it's gone - are there plans on readding it? If not, are there any workarounds?

Regards

**Comment by vanpra** [comment]
Hi, there are currently no plans on re-adding the datetime picker due to the fact that it's not an official material dialog type and the implementation added a lot of complexity. The only workaround right now is to open them up as separate dialogs and  then you can make the on click of the date dialog open up the time dialog.
