### ISSUE TITLE
NPE when using initialSelection=null and waitForPositiveButton=false for listItemsSingleChoince

### ISSUE THREAD

**Issue by Meegooo** [vanpra/compose-material-dialogs#83]
The title says it. If you try to use `listItemsSingeChoice`, don't supply it `initialSelection` parameter (or explicitly choose `null`), and then choose waitForPositiveButton = false, it will immideately crash with NullPointerException.

Problematic lines (every use of `selected!!`)
https://github.com/vanpra/compose-material-dialogs/blob/main/core/src/main/java/com/vanpra/composematerialdialogs/MaterialDialogLists.kt#L223-L241

It assumes that selection will never be null, which is false. The parameter in `onChoiceChange` should be nullable.]

PS. Didn't test, but I think that NPE will also appear if `initialSelection` is null and you try to click `positiveButton` without choosing an item first.

**Comment by vanpra** [comment]
Thanks for letting me know about this issue and it should be fixed in the 0.4.3 release. The reason for assuming that the selection will never be null is because the positive button is disabled until a selection is made. However, there was an issue when using waitForPositiveButton=false as the callback fired on the first composition when the value is null.
